### ISSUE TITLE
QuantumultX分流

### ISSUE THREAD

**Issue by ddgksf2013** [lwd-temp/anti-ip-attribution#1]
感谢提供，利用yml文件制作了下QuantumultX的分流（后面持续更新）

https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Filter/anti-ip-attribution.list

**Comment by anwen-anyi** [comment]
> 感谢提供，利用yml文件制作了下QuantumultX的分流（后面持续更新）
> 
> 
> 
> https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Filter/anti-ip-attribution.list

很抱歉 这么晚了打扰您，你好，不晓得是我配置的问题还是网络问题 添加到自定义策略后   点击PROXY 后 打开微信聊天记录图片的时候明显很慢了QAQ…
