### ISSUE TITLE
请求增加其乐论坛keylol.com

### ISSUE THREAD

**Issue by Nevidebla** [lwd-temp/anti-ip-attribution#11]
最近其乐论坛https://keylol.com/ 也开始显示IP属地了。并且每条评论都有独立的IP属地记录。

**Comment by DoingDog** [comment]
评论区
domain, keylol.com

**Comment by lwd-temp** [comment]
感谢，已添加。

**Comment by Nevidebla** [comment]
> 评论区 domain, keylol.com

你这也太粗暴了吧，直接把整个网站给代理了

**Comment by lwd-temp** [comment]
不是这样的，clash只能根据域名分流（SNI，不需要证书解密流量），如果API地址在这个域名下就只能这么写。
________________________________
