### ISSUE TITLE
注释好像不应该加在域名/IP后面的

### ISSUE THREAD

**Issue by justdoiting** [lwd-temp/anti-ip-attribution#13]
网站后面好像不应该加注释的，比如我自己做rule-providers，会把注释也带上，然后文件就报错了，一般格式是 匹配方式+域名/IP+策略，加了注释就没法添加策略了
![image](https://user-images.githubusercontent.com/109136320/181822798-62e9fce0-ee68-4b83-b14c-45ac30c6a8fb.png)

**Comment by lwd-temp** [comment]
在CFW的文档中，似乎允许在一个项目后出现注释。

可能由于这个特性不属于clash的原生特性，不同开发者对此有不同的实现。

在您的截图中，策略似乎放在了注释后面，这不是正确的规则格式。把策略直接加在逗号后面是否有帮助？

**Comment by justdoiting** [comment]
![rule](https://user-images.githubusercontent.com/109136320/181896953-0a7767c8-5ab3-4431-899e-3ced5a5e3c92.png)
![分组m](https://user-images.githubusercontent.com/109136320/181897011-7bd8987e-ba11-4fde-9539-a9011832beb1.png)
![链接](https://user-images.githubusercontent.com/109136320/181897018-69298feb-0ff3-4b0d-ac0f-f461f512299d.png)
![报错](https://user-images.githubusercontent.com/109136320/181897213-e3662177-7a6d-485a-85bb-0807fd2d0e7c.png)
报错

**Comment by lwd-temp** [comment]
那个文件似乎确实存在语法问题，但无法确定是否发生在注释上。

以下为lint后结果：

'''yaml
payload: 
  - DOMAIN-SUFFIX,biliapi.net
  - DOMAIN,api.bilibili.com
  - DOMAIN,api.bilibili.tv
  - DOMAIN,app.bilibili.com
  - DOMAIN-SUFFIX,biliapi.com
  - DOMAIN,api.live.bilibili.com
  - DOMAIN,api.vc.bilibili.com
  - DOMAIN,passport.bilibili.com
  - DOMAIN,live-trace.bilibili.com
  - DOMAIN,message.bilibili.com
  - DOMAIN,cm.bilibili.com
  - DOMAIN-SUFFIX,api.weibo.cn
  - DOMAIN-SUFFIX,api.weibo.com
  - DOMAIN,tieba.baidu.com
  - DOMAIN,tbmsg.baidu.com
  - DOMAIN,tb5.bdstatic.com
  - DOMAIN,fclog.baidu.com
  - DOMAIN,gsp0.baidu.com
  - DOMAIN,hm.baidu.com
  - DOMAIN,www.baidu.com
  - DOMAIN,szshort.weixin.qq.com
  - DOMAIN,szextshort.weixin.qq.com
  - DOMAIN,szminorshort.weixin.qq.com
  - DOMAIN,mp.weixin.qq.com
  - DOMAIN-SUFFIX,zhihu.com
  - IP-CIDR,103.41.167.0/24
  - DOMAIN-KEYWORD,core-c-lq
  - DOMAIN-KEYWORD,core-lq
  - DOMAIN-KEYWORD,normal-c-lq
  - DOMAIN-KEYWORD,normal-lq
  - DOMAIN-KEYWORD,search-quic-lq
  - DOMAIN-KEYWORD,search-lq
  - DOMAIN-SUFFIX,toutiaoapi.com
  - DOMAIN-SUFFIX,gifshow.com
  - DOMAIN-SUFFIX,ksapisrv.com
  - DOMAIN-SUFFIX,xiaohongshu.com
  - DOMAIN,keylol.com
  - DOMAIN-SUFFIX,ixigua.com
  - DOMAIN,www.wenshushu.cn
'''

**Comment by justdoiting** [comment]
https://github.com/justdoiting/clash-rule/blob/main/IPFake.yaml
把域名后面的注释删掉就可以用了
![可以](https://user-images.githubusercontent.com/109136320/181904193-c01f03a9-a0db-4c1c-a05f-9b0843a80529.png)

**Comment by lwd-temp** [comment]
好的，已修复。
