### ISSUE TITLE
求豆瓣ip接口

### ISSUE THREAD

**Issue by user-github-2333** [lwd-temp/anti-ip-attribution#14]

**Comment by DoingDog** [comment]
ios 客户端测试有效 其他环境待测试
发动态和个人主页显示代理ip 可引起卡顿

ip-cidr,49.233.242.15/32
ip-cidr,81.70.124.99/32
ip-cidr,140.143.177.206/32

**Comment by user-github-2333** [comment]
> 

动态和评论是有效的，主页应该要过一段时间才能变更

**Comment by user-github-2333** [comment]
> ios 客户端测试有效 其他环境待测试 发动态和个人主页显示代理ip 可引起卡顿
> 
> ip-cidr,49.233.242.15/32 ip-cidr,81.70.124.99/32 ip-cidr,140.143.177.206/32
> 
> 修改：已失效

动态和评论是有效的，主页应该要过一段时间才能变更

**Comment by DoingDog** [comment]
ios客户端接口 再次测试，仍然有效

网页端发动态接口 domain,www.douban.com



> ios 客户端测试有效 其他环境待测试 发动态和个人主页显示代理ip 可引起卡顿
> 
> ip-cidr,49.233.242.15/32 ip-cidr,81.70.124.99/32 ip-cidr,140.143.177.206/32
> 
> 修改：已失效

**Comment by lwd-temp** [comment]
感谢，已添加。

**Comment by DoingDog** [comment]
https://dns.google/resolve?name=frodo.douban.com&type=A

dns.google 解析此ip地址得到结果和三个ip规则一致 暂时没有发生变化

{
      "name": "frodo.douban.com.",
      "type": 5 /* CNAME */,
      "TTL": 244,
      "data": "forward.douban.com."
    },
    {
      "name": "forward.douban.com.",
      "type": 5 /* CNAME */,
      "TTL": 30,
      "data": "tc.forward.douban.com."
    },
    {
      "name": "tc.forward.douban.com.",
      "type": 1 /* A */,
      "TTL": 300,
      "data": "140.143.177.206"
    },
    {
      "name": "tc.forward.douban.com.",
      "type": 1 /* A */,
      "TTL": 300,
      "data": "49.233.242.15"
    },
    {
      "name": "tc.forward.douban.com.",
      "type": 1 /* A */,
      "TTL": 300,
      "data": "81.70.124.99"
    }

**Comment by lwd-temp** [comment]
> https://dns.google/resolve?name=frodo.douban.com&type=A
> 
> dns.google 解析此ip地址得到结果和三个ip规则一致 暂时没有发生变化
> 
> { "name": "frodo.douban.com.", "type": 5 /* CNAME _/, "TTL": 244, "data": "forward.douban.com." }, { "name": "forward.douban.com.", "type": 5 /_ CNAME _/, "TTL": 30, "data": "tc.forward.douban.com." }, { "name": "tc.forward.douban.com.", "type": 1 /_ A _/, "TTL": 300, "data": "140.143.177.206" }, { "name": "tc.forward.douban.com.", "type": 1 /_ A _/, "TTL": 300, "data": "49.233.242.15" }, { "name": "tc.forward.douban.com.", "type": 1 /_ A */, "TTL": 300, "data": "81.70.124.99" }

我开始不太明白了，可以帮忙写一下规则吗？

**Comment by DoingDog** [comment]
有两种吧

ip-cidr,119.29.29.98/32,reject
domain,frodo.douban.com,proxy

或者

ip-cidr,49.233.242.15/32,proxy
ip-cidr,81.70.124.99/32,proxy
ip-cidr,140.143.177.206/32,proxy
domain,frodo.douban.com,proxy


暂时都是有效的，但第二种不排除失效的可能性

**Comment by lwd-temp** [comment]
感谢，已添加。
