### ISSUE TITLE
用了哔哩哔哩刷新不了加载不出来

### ISSUE THREAD

**Issue by Rone89** [lwd-temp/anti-ip-attribution#2]

**Comment by lwd-temp** [comment]
个人猜测应该是速度太慢，在我这里测试没有明显问题。
请提供开发人员工具网络日志，或者生成HAR文件上传。

**Comment by lwd-temp** [comment]
非常抱歉，但此问题属个别现象且无法复现。由于您在一段时间内尚未提交进一步故障信息，此issue将关闭。如有需要可以再次打开。
