### ISSUE TITLE
After yesterday's update, there was a problem

### ISSUE THREAD

**Issue by 0ox** [lwd-temp/anti-ip-attribution#20]
After yesterday's update, Surge updates external resource tips:

`Failed to parse remote resource data`

**Comment by 0ox** [comment]
> After yesterday's update, Surge updates external resource tips:
> 
> `Failed to parse remote resource data`

[This update](https://github.com/lwd-temp/anti-ip-attribution/commit/c9c298147126becf53a3e272044ec531e41ec3f3)

**Comment by DoingDog** [comment]
HOST is only for QX,it should be DOMAIN instead...

**Comment by DoingDog** [comment]
@lwd-temp

**Comment by lwd-temp** [comment]
Sorry, my bad.

Fixed.
