### ISSUE TITLE
求網易雲音樂評論的IP接口。

### ISSUE THREAD

**Issue by RA1SUor** [lwd-temp/anti-ip-attribution#21]
自己只找到music.163.com、163.com、126.com、netease.com這幾個主界面的域名。

**Comment by lwd-temp** [comment]
网页端主要为music.163.com、163.com，手机客户端还有man.netease.com、*.music.163.com、*.163.com等。

个人猜测*.music.163.com主要提供API，其他域名可能为图片CDN等，处于谨慎考虑尝试添加所有域名。

**Comment by lwd-temp** [comment]
不过我没发现网易云音乐有显示IP归属地，无法确定是否有效。

先待处理吧，等到能验证的时候。

**Comment by DoingDog** [comment]
在ios客户端和网页版，无论是评论区还是个人主页都没有发现ip地址显示

如果记录了ip,猜测api为music.163.com interface.music.163.com 但现在无法验证

**Comment by RA1SUor** [comment]
感謝回復，我也覺得music.163.com interface.music.163.com為主要判斷接口。只是我走把上面的域名都加進規則以後，不會跳海外版權提示。

**Comment by DoingDog** [comment]
个人主页开始显示ip，准备验证

**Comment by lwd-temp** [comment]
`nstool.netease.com` 有点可疑，请注意一下。

**Comment by lwd-temp** [comment]
似乎会根据一段时间内的IP属地进行判断，短期内不会变化。

**Comment by DoingDog** [comment]
个人主页验证有效

**Comment by DoingDog** [comment]
music.163.com interface.music.163.com 代理后，个人主页显示代理ip

但无法验证两个都是api地址

**Comment by DoingDog** [comment]
> `[nstool.netease.com](http://nstool.netease.com)` 有点可疑，请注意一下。

此地址命中我QX的拦截规则，准备放行后再次测试

**Comment by lwd-temp** [comment]
Web版API是`music.163.com`可以确定，观测到App还会请求`interface3.music.163.com`，不确定有没有必要处理整个`*.music.163.com`

**Comment by DoingDog** [comment]
> `[nstool.netease.com](http://nstool.netease.com)` 有点可疑，请注意一下。

此地址，还有 *.laiqukankan.com 似乎不影响个人主页ip。正在ios客户端尝试仅代理 music.163.com

**Comment by RA1SUor** [comment]
经实测，只添加那几个域名仍会显示真实地址。
但是IP地址是实时更新的。
这是打开网易云之后Charles的抓包记录（时间顺序）：

- nstool.netease.com
- mam.netease.com
- wanproxy.127.net
- dt.netease.im
- api.iplay.163.com
- api.k.163.com
- lbs.netease.im
- wannos.127.net
- interface3.music.163.com
- ac.dun.163.com
- *.music.126.net

猜测wanproxy.127.net也会影响IP的变动。

**Comment by lwd-temp** [comment]
考虑全部加入进去，音乐CDN不包括在内
________________________________

**Comment by DoingDog** [comment]
仅代理music.163.com失败。正在尝试代理music.163.com interface3.music.163.com interface.music.163.com

**Comment by DoingDog** [comment]
测试个人主页ip可能需要2天才会更新

**Comment by RA1SUor** [comment]
> 测试个人主页ip可能需要2天才会更新

可能会检测网络是否采用代理，
我在路由器端部署Clash能立即改变属地。
打开网易云时还会向59.111.19.*（网易广州）、112.13.112.*（中国移动）发送请求。
如果靠这俩判断iP的话，很难通过规则来拦截。

**Comment by DoingDog** [comment]
> > 测试个人主页ip可能需要2天才会更新
> 
> 可能会检测网络是否采用代理， 我在路由器端部署Clash能立即改变属地。 打开网易云时还会向59.111.19.53（网易广州）、112.13.112.4（中国移动）以及类似地址发送请求。 如果靠这俩判断iP的话，很难通过规则来拦截。

可能httpdns

**Comment by DoingDog** [comment]
https://dns.google/query?name=interface.music.163.com&rr_type=A&ecs=211.136.23.43

**Comment by lwd-temp** [comment]
Bing搜索收录了这个链接，可能会有所帮助
https://lbs.netease.im/lbs/conf.jsp

内容如下：

`{"common":{"httpdns":["https://httpdns.n.netease.com","http://59.111.239.61","http://59.111.239.62"],"nos":["http://45.127.128.24","http://45.127.128.25"],"link":["59.111.209.132:8080","59.111.36.158:8080","59.111.209.101:8080","59.111.232.34:8080","59.111.232.144:8080","59.111.232.74:8080","59.111.232.9:8080","59.111.232.75:8080","link-yqsx01.netease.im:8080"],"nosdl":"http://nos.netease.com","lbs":"https://lbs.netease.im/lbs/conf.jsp","link.default":["link.netease.im:8080"],"nosdls":["http://nos.netease.com"],"desc":"online"}}`

**Comment by DoingDog** [comment]
测试完毕，将 单域名 music.163.com interface3.music.163.com interface.music.163.com 代理后，ip从国内变为国外

但是 interface3.music.163.com 存在httpdns，测试用的是QX开启了DNS劫持功能，不保证其他代理工具，不开启劫持功能也有效

**Comment by DoingDog** [comment]
domain,interface.music.163.com
domain,interface3.music.163.com
domain,music.163.com

收集了httpdns解析后连接的cname地址

telv4.music.ntes53.netease.com
telv6.music.ntes53.netease.com
cmccv4.music.ntes53.netease.com
cmccv6.music.ntes53.netease.com
univ4.music.ntes53.netease.com
univ6.music.ntes53.netease.com
overseasv4.music.ntes53.netease.com
overseasv6.music.ntes53.netease.com
bgpv4.music.ntes53.netease.com
bgpv6.music.ntes53.netease.com

对应ip

ip-cidr,101.71.154.241/32
ip-cidr,103.126.92.132/32
ip-cidr,103.126.92.133/32
ip-cidr,112.13.119.18/32
ip-cidr,112.13.122.4/32
ip-cidr,115.236.118.34/32
ip-cidr,115.236.121.4/32
ip-cidr,45.254.48.1/32
ip-cidr,59.111.160.195/32
ip-cidr,59.111.19.33/32
ip-cidr,59.111.19.53/32

**Comment by lwd-temp** [comment]
感谢，稍后具体处理规则。
________________________________
