### ISSUE TITLE
知乎 iOS 端使用规则后仍然泄露真实IP属地

### ISSUE THREAD

**Issue by KooriMoe** [lwd-temp/anti-ip-attribution#24]
测试版本：知乎 iOS 8.30.0 (10713) + Quantumult X
个人推测可能是通过 HTTPDNS 对 IP 属地进行判断
尝试抓包后发现知乎app会尝试请求 HTTPDNS 对服务域名解析。
```
118.89.204.198: HTTPDNS
[2402:4e00:1200:ed00:0:9089:6dac:96b6]: HTTPDNS
```
<img width="1408" alt="截屏2022-08-19 上午11 59 22" src="https://user-images.githubusercontent.com/39030261/185541701-478cae5b-c19c-4ca8-8772-df363d46625d.png">

将以上两个 HTTPDNS 加入到 REJECT 规则后仍无效，且观察发表评论的请求仍然是以 IP 形式而并非 `api.zhihu.com` 发送请求。

**Comment by KooriMoe** [comment]
目前在 Quantumult X 测试将 118.89.204.198/23 添加 REJECT 规则后可以阻止知乎 iOS 端获取真实 IP 属地。   
![image](https://user-images.githubusercontent.com/39030261/185860915-969ad7ad-c351-4284-bf94-ca375e93e0c1.jpeg)

**Comment by lwd-temp** [comment]
感谢，已Merge
