### ISSUE TITLE
B站的新版本客户端评论地区又不行了

### ISSUE THREAD

**Issue by Rakau** [lwd-temp/anti-ip-attribution#27]
RT，6.89.0，有时候会漏

**Comment by lwd-temp** [comment]
有点困难啊...

-----

![92629644_p0](https://user-images.githubusercontent.com/26019675/189617265-bab66659-8fd8-41cf-9216-0051bee141d1.png)
[Source](https://www.pixiv.net/artworks/92629644)

**Comment by Rakau** [comment]
> 有点困难啊...
> 
> ![92629644_p0](https://user-images.githubusercontent.com/26019675/189617265-bab66659-8fd8-41cf-9216-0051bee141d1.png) [Source](https://www.pixiv.net/artworks/92629644)

找到原因了，在B站客户端设置-其它设置-自动网络维护里的网络服务，用服务2就行

**Comment by Rakau** [comment]
> > 有点困难啊...
> > 
> > ![92629644_p0](https://user-images.githubusercontent.com/26019675/189617265-bab66659-8fd8-41cf-9216-0051bee141d1.png) [Source](https://www.pixiv.net/artworks/92629644)
> 
> 找到原因了，在B站客户端设置-其它设置-自动网络维护里的网络服务，用服务2就行

不过服务1的ip不知道怎么抓
