### ISSUE TITLE
快手评论区ip

### ISSUE THREAD

**Issue by DoingDog** [lwd-temp/anti-ip-attribution#3]
domain-suffix, gifshow.com

个人主页似乎有延迟，未测试

**Comment by lwd-temp** [comment]
已添加，见`e0b514f3f1831e0fa33eb39ec4ce20a27a94fa80`，感谢贡献。

**Comment by DoingDog** [comment]
经过测试发现节点网络较差时 评论区有概率显示真实ip
加上一条就行了
domain-suffix, ksapisrv.com

个人主页有延迟，开全局也无解

**Comment by DoingDog** [comment]
domain-suffix, ksapisrv.com
domain-suffix, gifshow.com

一个域名连不上会请求另一个，两个同时使用就会生效了

**Comment by lwd-temp** [comment]
已添加，感谢贡献。
