### ISSUE TITLE
抖音规则

### ISSUE THREAD

**Issue by Wittoy** [lwd-temp/anti-ip-attribution#33]
这边测试的一点点发现
针对 `amemv.com` 域名下的 `-normal-` 关键词代理就能实现IP归属地修改。如果对全局域名进行代理的话，请求的视频内容大部分来自海外cdn。

**Comment by lwd-temp** [comment]
规则似乎不能同时对`amemv.com`和`-normal-`进行筛选。

这么说，感觉只留下keyword的`-normal-`就可以了？

**Comment by Wittoy** [comment]
> 这么说，感觉只留下keyword的就可以了？ 

我这边测试可以，实际效果还需要更多人的反馈

**Comment by Wittoy** [comment]
Update:

```
- DOMAIN-KEYWORD,-normal-hl
- DOMAIN-KEYWORD,-normal-c-hl
- DOMAIN-KEYWORD,-core-c-hl

- DOMAIN-KEYWORD,-normal-lf
- DOMAIN-KEYWORD,-normal-c-lf
- DOMAIN-KEYWORD,-core-c-lf
```

> 规则似乎不能同时对`amemv.com`和`-normal-`进行筛选。

这边的方法是对以下域名走直连

```
- DOMAIN-SUFFIX,zijieapi.com,DIRECT
- DOMAIN-SUFFIX,ecombdapi.com,DIRECT
```

**Comment by lwd-temp** [comment]
> Update:
> 
> ```
> - DOMAIN-KEYWORD,-normal-hl
> - DOMAIN-KEYWORD,-normal-c-hl
> - DOMAIN-KEYWORD,-core-c-hl
> 
> - DOMAIN-KEYWORD,-normal-lf
> - DOMAIN-KEYWORD,-normal-c-lf
> - DOMAIN-KEYWORD,-core-c-lf
> ```
> 
> > 规则似乎不能同时对`amemv.com`和`-normal-`进行筛选。
> 
> 这边的方法是对以下域名走直连
> 
> ```
> - DOMAIN-SUFFIX,zijieapi.com,DIRECT
> - DOMAIN-SUFFIX,ecombdapi.com,DIRECT
> ```

https://github.com/lwd-temp/anti-ip-attribution/commit/2b042a331ba25a16f3a9a8ac59ce5b55e85f15f5
