### ISSUE TITLE
百度的不能用，删了吧。

### ISSUE THREAD

**Issue by GodFreedom** [lwd-temp/anti-ip-attribution#35]

**Comment by GodFreedom** [comment]
我指的是贴吧

**Comment by lwd-temp** [comment]
理论上，贴吧网页版应该还是能用的。
有时间会进一步调查。

**Comment by Wittoy** [comment]
安卓客户端目测是根据HTTPDNS来判断，HTTPDNS服务器是百度自家Public DNS `180.76.76.0/24` 段
该段开放HTTP端口的有这些
```
180.76.76.112
180.76.76.200
```
e.g. http://180.76.76.112//
其SSL证书对应域名是 `httpsdns.baidu.com`

**Comment by lwd-temp** [comment]
已更新。
