### ISSUE TITLE
米游社&小黑盒

### ISSUE THREAD

**Issue by Wittoy** [lwd-temp/anti-ip-attribution#39]
米游社主域名已从 `bbs.mihoyo.com` 302至 `miyoushe.com`
```
- DOMAIN,bbs-api.mihoyo.com
- DOMAIN,bbs-api.miyoushe.com
```
小黑盒主域名，包括文章之类（图片CDN等静态资源不在此域名范围内）
```
- DOMAIN,api.xiaoheihe.cn
```

**Comment by lwd-temp** [comment]
非常感谢，已更新。

https://github.com/lwd-temp/anti-ip-attribution/commit/2e81800f2e335300ea8ac5669eabd42de12739bc

**Comment by Wittoy** [comment]
> 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用

小黑盒的话域名换成 `data.xiaoheihe.cn` 了

**Comment by zqhaqha** [comment]
> > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> 
> 小黑盒的话域名换成 `data.xiaoheihe.cn` 了

试过了,我刚才还抓包来着,好几个域名,一大堆ip都加入规则都弄了,没作用,我的页面右上角直接显示的还是本地的ip,

**Comment by zqhaqha** [comment]
> > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> 
> 小黑盒的话域名换成 `data.xiaoheihe.cn` 了

酷安,小黑盒,都不管用了,我甚至不信邪刚从还更新了软路由固件...

**Comment by Wittoy** [comment]
> > > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> > 
> > 
> > 小黑盒的话域名换成 `data.xiaoheihe.cn` 了
> 
> 试过了,我刚才还抓包来着,好几个域名,一大堆ip都加入规则都弄了,没作用,我的页面右上角直接显示的还是本地的ip,

尝试阻止 iPv6 & QUIC & HTTPDNS 等邪门手段

**Comment by zqhaqha** [comment]
> > > > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> > > 
> > > 
> > > 小黑盒的话域名换成 `data.xiaoheihe.cn` 了
> > 
> > 
> > 试过了,我刚才还抓包来着,好几个域名,一大堆ip都加入规则都弄了,没作用,我的页面右上角直接显示的还是本地的ip,
> 
> 尝试阻止 iPv6 & QUIC & HTTPDNS 等邪门手段

刚刚试了禁止解析 IPv6 DNS 记录,酷安正常使用规则了,但是小黑盒还是不行,我清除了小黑盒数据,删了软件从新下载安装,都不行

**Comment by zqhaqha** [comment]
> > > > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> > > 
> > > 
> > > 小黑盒的话域名换成 `data.xiaoheihe.cn` 了
> > 
> > 
> > 试过了,我刚才还抓包来着,好几个域名,一大堆ip都加入规则都弄了,没作用,我的页面右上角直接显示的还是本地的ip,
> 
> 尝试阻止 iPv6 & QUIC & HTTPDNS 等邪门手段
,,,
最新情况,在passwall2的dns设置里,吧需要代理的分流规则域名使用 FakeDNS,小黑盒,终于正常了,,,,,太难了

**Comment by Wittoy** [comment]
> > > > > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> > > > 
> > > > 
> > > > 小黑盒的话域名换成 `data.xiaoheihe.cn` 了
> > > 
> > > 
> > > 试过了,我刚才还抓包来着,好几个域名,一大堆ip都加入规则都弄了,没作用,我的页面右上角直接显示的还是本地的ip,
> > 
> > 
> > 尝试阻止 iPv6 & QUIC & HTTPDNS 等邪门手段
> > ,,,
> > 最新情况,在passwall2的dns设置里,吧需要代理的分流规则域名使用 FakeDNS,小黑盒,终于正常了,,,,,太难了

小黑盒的IP归属判断规则是不定时的，理论上多退出登录就行了

**Comment by zqhaqha** [comment]
> > > > > > 貌似规则更新好了还是怎么样,现在我设置了分流,丝毫不起作用
> > > > > 
> > > > > 
> > > > > 小黑盒的话域名换成 `data.xiaoheihe.cn` 了
> > > > 
> > > > 
> > > > 试过了,我刚才还抓包来着,好几个域名,一大堆ip都加入规则都弄了,没作用,我的页面右上角直接显示的还是本地的ip,
> > > 
> > > 
> > > 尝试阻止 iPv6 & QUIC & HTTPDNS 等邪门手段
> > > ,,,
> > > 最新情况,在passwall2的dns设置里,吧需要代理的分流规则域名使用 FakeDNS,小黑盒,终于正常了,,,,,太难了
> 
> 小黑盒的IP归属判断规则是不定时的，理论上多退出登录就行了

嗯嗯多谢,现在小黑盒和酷安都正常了,使用一段看看
