### ISSUE TITLE
clash-provider中后接策略组似乎是无效的

### ISSUE THREAD

**Issue by 1045925330** [lwd-temp/anti-ip-attribution#42]
![image](https://github.com/lwd-temp/anti-ip-attribution/assets/30003970/370ddd53-64b4-444c-9f60-99eb6a7c1fde)
![image](https://github.com/lwd-temp/anti-ip-attribution/assets/30003970/0b7f8140-c53e-456e-a4c3-7113df3dfb8c)

**Comment by lwd-temp** [comment]
目前，可以使用`rule-provider-direct.yaml` `rule-provider-proxy.yaml` `rule-provider-reject.yaml`。

未来可能会尝试将DIRECT和BLOCK提前，看看会不会解决问题。

相关issue：https://github.com/lwd-temp/anti-ip-attribution/issues/23#issuecomment-1224150101
