### ISSUE TITLE
请在clash等IP分流规则添加no-resolve防DNS泄漏

### ISSUE THREAD

**Issue by yoshyv** [lwd-temp/anti-ip-attribution#43]
你好

读rules.yaml后发现有IP-CIDR和IP-CIDR6的分流。如果简单的把这个ruleset分流到某节点，并且这个ruleset在国外站点domain类分流规则上面（优先级高）的情况下会导致访问国外站全部过一遍dns解析，哪怕国外domain类分流有匹配规则。此时会导致dns泄漏。

domain和ip规则混合的情况下只能用classical类型behavior，然而clash对于非ipcidr类型的ruleset无法整个ruleset添加no-resolve。

麻烦在每条IP-CIDR规则后面添加 no-resolve 选项，（帮助小白）避免dns泄漏发生。

谢谢。

**Comment by lwd-temp** [comment]
问题已收到，目前的生成脚本有些混乱，在整理后会添加此功能。

**Comment by lwd-temp** [comment]
https://github.com/lwd-temp/anti-ip-attribution/pull/45
