### ISSUE TITLE
Does it support Shadowrocket?

### ISSUE THREAD

**Issue by Hsiao-Feng** [lwd-temp/anti-ip-attribution#48]
Is there a config of [Shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118) available? Thanks.

**Comment by lwd-temp** [comment]
TODO

Contribution Welcomed.

**Comment by Hsiao-Feng** [comment]
> TODO
> 
> Contribution Welcomed.

Thanks for your help! 😃

**Comment by Hsiao-Feng** [comment]
> TODO
> 
> Contribution Welcomed.

Hi. After testing, [surge.list](https://github.com/lwd-temp/anti-ip-attribution/blob/main/generated/surge.list) can be directly applied to Shadowrocket. So no need to create new config for Shadowrocket, my problem is solved. Thank you ;)

Hope you have a good day.
