### ISSUE TITLE
用了分流规则后，导致B站电脑网页端视频播放卡顿

### ISSUE THREAD

**Issue by Nevidebla** [lwd-temp/anti-ip-attribution#49]
虽然在clash for window的log里面显示视频资源访问的是直连，但是rule模式下确实明显卡顿，切换成direct模式立马流畅。

**Comment by lwd-temp** [comment]
目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？

**Comment by Meina9758** [comment]
> 目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？

目前确定的只将*.bilibili.com内容进行代理，在播放视频时不卡顿，PC端发送评论IP为代理地IP，但是IOS端依旧泄露真实IP地址，在2023.10.18之前将www.bilibili.com重定向至i.w.bilicdn1.com即可，目前只生效PC端，有理由怀疑和知乎一样使用了端内HTTPSDNS，因为在开启抓包VPN后显示代理地IP

**Comment by Meina9758** [comment]
> > 目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？
> 
> 目前确定的只将*.bilibili.com内容进行代理，在播放视频时不卡顿，PC端发送评论IP为代理地IP，但是IOS端依旧泄露真实IP地址，在2023.10.18之前将www.bilibili.com重定向至i.w.bilicdn1.com即可，目前只生效PC端，有理由怀疑和知乎一样使用了端内HTTPSDNS，因为在开启抓包VPN后显示代理地IP

另*发送动态和评论似乎并非同检测手段

**Comment by Meina9758** [comment]
> 目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？

请关闭Issue

**Comment by MoriMeina** [comment]
> > > 目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？
> > 
> > 
> > 目前确定的只将*.bilibili.com内容进行代理，在播放视频时不卡顿，PC端发送评论IP为代理地IP，但是IOS端依旧泄露真实IP地址，在2023.10.18之前将www.bilibili.com重定向至i.w.bilicdn1.com即可，目前只生效PC端，有理由怀疑和知乎一样使用了端内HTTPSDNS，因为在开启抓包VPN后显示代理地IP
> 
> 好像失效了，又开始卡了

视频加载卡顿？还是缓冲卡顿？

**Comment by MoriMeina** [comment]
> > > > 目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？
> > > 
> > > 
> > > 目前确定的只将*.bilibili.com内容进行代理，在播放视频时不卡顿，PC端发送评论IP为代理地IP，但是IOS端依旧泄露真实IP地址，在2023.10.18之前将www.bilibili.com重定向至i.w.bilicdn1.com即可，目前只生效PC端，有理由怀疑和知乎一样使用了端内HTTPSDNS，因为在开启抓包VPN后显示代理地IP
> > 
> > 
> > 好像失效了，又开始卡了
> 
> 视频加载卡顿？还是缓冲卡顿？
> 目前考虑将内容CDN、视频CDN加入直连，稍后提起PR

**Comment by MoriMeina** [comment]
> > > 目前的规则是比较过激的，确实有可能代理非必要API导致反应迟缓，但由于Clash本身不支持domain (suffix)以外的指定方式，可能没有更好的优化方法？
> > 
> > 
> > 目前确定的只将*.bilibili.com内容进行代理，在播放视频时不卡顿，PC端发送评论IP为代理地IP，但是IOS端依旧泄露真实IP地址，在2023.10.18之前将www.bilibili.com重定向至i.w.bilicdn1.com即可，目前只生效PC端，有理由怀疑和知乎一样使用了端内HTTPSDNS，因为在开启抓包VPN后显示代理地IP
> 
> 好像失效了，又开始卡了

PR#52

**Comment by Ghroth-follower** [comment]
时不时卡顿原因是代理了非视频CDN以外的api，会导致哔哩哔哩的视频流和直播流切换到海外cdn
然而海外cdn会受到国内网络风控影响，导致抽风绕路还丢包，(部分)bilivideo.com和akamaized.net都会这样

关掉代理或者切换成direct不卡了是因为不会再定向到那几个海外专用cdn了，会变回国内cdn

**Comment by MoriMeina** [comment]
> > 时不时卡顿原因是代理了非视频CDN以外的api，会导致哔哩哔哩的视频流和直播流切换到海外cdn 然而海外cdn会受到国内网络风控影响，导致抽风绕路还丢包，(部分)bilivideo.com和akamaized.net都会这样
> > 关掉代理或者切换成direct不卡了是因为不会再定向到那几个海外专用cdn了，会变回国内cdn
> > 所以手动标注视频cdn直连还是依然有卡顿现象，是十分正常的 而且如果用户没有刻意在配置里面写代理所有非大陆流量，这几个视频cdn也不会主动的被代理，默认都会是直连
> 
> 所以说，目前有办法实现，仅代理涉及用户主页ip属地、投稿ip属地、发评论ip属地的api，而不代理负责分配CDN的api吗？

有点困难，目前无法定位视频CDN分配api。就算能够定位，按照目前的代理规则来说，因为所有的API在一个域名上，无法分开进行代理

**Comment by MoriMeina** [comment]
> > > > 时不时卡顿原因是代理了非视频CDN以外的api，会导致哔哩哔哩的视频流和直播流切换到海外cdn 然而海外cdn会受到国内网络风控影响，导致抽风绕路还丢包，(部分)bilivideo.com和akamaized.net都会这样
> > > > 关掉代理或者切换成direct不卡了是因为不会再定向到那几个海外专用cdn了，会变回国内cdn
> > > > 所以手动标注视频cdn直连还是依然有卡顿现象，是十分正常的 而且如果用户没有刻意在配置里面写代理所有非大陆流量，这几个视频cdn也不会主动的被代理，默认都会是直连
> > > 
> > > 
> > > 所以说，目前有办法实现，仅代理涉及用户主页ip属地、投稿ip属地、发评论ip属地的api，而不代理负责分配CDN的api吗？
> > 
> > 
> > 有点困难，目前无法定位视频CDN分配api。就算能够定位，按照目前的代理规则来说，因为所有的API在一个域名上，无法分开进行代理
> 
> 或者曲线救国一下？好像之前见过有那种B站的插件，可以强制锁定国内的CDN？我记得之前有那种解锁海外番剧的插件，就能让你既被识别为海外，还继续用的国内CDN传输视频流。

Clash主要受众是移动端和路由代理，PC端网页插件很好找，没有实际意义

**Comment by MoriMeina** [comment]
> > > > 时不时卡顿原因是代理了非视频CDN以外的api，会导致哔哩哔哩的视频流和直播流切换到海外cdn 然而海外cdn会受到国内网络风控影响，导致抽风绕路还丢包，(部分)bilivideo.com和akamaized.net都会这样
> > > > 关掉代理或者切换成direct不卡了是因为不会再定向到那几个海外专用cdn了，会变回国内cdn
> > > > 所以手动标注视频cdn直连还是依然有卡顿现象，是十分正常的 而且如果用户没有刻意在配置里面写代理所有非大陆流量，这几个视频cdn也不会主动的被代理，默认都会是直连
> > > 
> > > 
> > > 所以说，目前有办法实现，仅代理涉及用户主页ip属地、投稿ip属地、发评论ip属地的api，而不代理负责分配CDN的api吗？
> > 
> > 
> > 有点困难，目前无法定位视频CDN分配api。就算能够定位，按照目前的代理规则来说，因为所有的API在一个域名上，无法分开进行代理
> 
> 或者曲线救国一下？好像之前见过有那种B站的插件，可以强制锁定国内的CDN？我记得之前有那种解锁海外番剧的插件，就能让你既被识别为海外，还继续用的国内CDN传输视频流。

请右键查看视频统计信息，反馈给我。可能能进行一些调整

**Comment by A1ca7raz** [comment]
视频CDN可以通过强行更改的方式解决，那请问直播CDN该如何修改呢，关于直播CDN的信息我没有搜到相关的信息

**Comment by MoriMeina** [comment]
> cn-hk-eq-01-14.bilivideo.com

看上去是分配到B站自己的CDN了，考虑更换节点再试试吧，这个目前没有什么好的办法
