### ISSUE TITLE
微博的规则不全，会显示真实IP

### ISSUE THREAD

**Issue by Nevidebla** [lwd-temp/anti-ip-attribution#5]
我访问微博首页显示是代理IP，但是发表微博和评论后，就成了本地IP了。

**Comment by lwd-temp** [comment]
已修改为`DOMAIN-SUFFIX,api.weibo.cn`，或许对解决问题有帮助。

只使用Web端是否仍然有问题？

**Comment by Nevidebla** [comment]
我一直是电脑web端。
刚才试了，还是不行。估计微博不是或者不只是通过api.weibo这个域名进行IP界定的。
而且微博是分为国内站、北美站、港澳站这类的不同版本的，界定标准是用户的访问IP。用这个clash规则照样会把我定位到国内站，开全局才能到北美站。

**Comment by lwd-temp** [comment]
这样的话可能需要weibo全站，微博图片视频CDN不在同一个域名下。
________________________________

**Comment by fmz200** [comment]
HOST-SUFFIX,weibo.cn
HOST-SUFFIX,weibo.com
HOST-SUFFIX,weibocdn.com
HOST-KEYWORD,weibo
# 试试这样吧

**Comment by lwd-temp** [comment]
> HOST-SUFFIX,weibo.cn HOST-SUFFIX,weibo.com HOST-SUFFIX,weibocdn.com HOST-KEYWORD,weibo
> 
> # 试试这样吧

感谢，已加入。
