### ISSUE TITLE
B站IOS端再次露地址

### ISSUE THREAD

**Issue by Meina9758** [lwd-temp/anti-ip-attribution#51]
屏蔽阿里HTTPSDNS网段后依然露地址，怀疑新增HTTPSDNS地址

**Comment by Meina9758** [comment]
> 屏蔽阿里HTTPSDNS网段后依然露地址，怀疑新增HTTPSDNS地址

IOS端使用Stream抓包时并不会露地址，一旦关闭Stream并重启客户端后地址露的干干净净
动态、评论都露，在此之前测试仅评论露地址
尝试在网关设备进行抓包，后续跟进

**Comment by Meina9758** [comment]
![Uploading 屏幕截图 2023-11-27 015629.png…]()
草（一种植物

**Comment by Meina9758** [comment]
![屏幕截图 2023-11-27 015629](https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/e43a7100-1c1b-49ab-b9a3-d6dc59c63920)
草（一种植物

**Comment by Meina9758** [comment]
![屏幕截图 2023-11-27 021315](https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/e547af69-acd3-4ba5-9720-b86be3b12fab)
POST /x/v2/reply/add HTTP/2
Host: api.bilibili.com
Cookie: _uuid=;
 bili_ticket=
; bili_jct=; sid=
Content-Length: 991
Content-Type: application/x-www-form-urlencoded
X-Bili-Ticket: 
App-Key: iphone
Session_id: 
Env: prod
X-Bili-Trace-Id: 
User-Agent: bili-universal/75600100 CFNetwork/1.0 Darwin/23.0.0 os/ios model/iPhone 13 mobi_app/iphone build/75600100 osVer/17.0.3 network/2 channel/AppStore
X-Bili-Aurora-Eid: U1wBT1MGUg==
Buvid: Y24BA523DB03521E430AA6B8AAB9769995A3
X-Bili-Mid: 28092263
Accept-Encoding: gzip, deflate

access_key=
评论的请求，隐藏了关键ID，应该不影响看

**Comment by Meina9758** [comment]
目前测试完毕，httpdns.bilivideo.com返回空记录或者直接拒绝即可
clash中仅配置
- DOMAIN-SUFFIX,bilibili.com
即可
其他域名与评论无关，biliapi.net是在api.bilibili.com无法使用时调用的，如果担心自行添加

**Comment by Meina9758** [comment]
等作者修改后请自行关闭，有意可以拉我进项目(最近也在研究这些

**Comment by Meina9758** [comment]
> 已更新，非常感谢。
> 
> [ed95522](https://github.com/lwd-temp/anti-ip-attribution/commit/ed9552256ebb210b2b78aa0f9fdd88f4f9a5567d)

有一个问题，单reject了httpdns.bilivideo.com之后其实还是露，根据最新的抓包来看其实还有dns.google的httpsDNS
![屏幕截图 2023-11-28 005102](https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/fb4b4297-6a81-439c-a422-833a32bc9659)
---

在我抓包时就走了这几条请求去httpsDNS，但是一旦离开抓包环境，评论、动态地址直接完全泄露，排除了移动网络影响，目前还在跟进

**Comment by Meina9758** [comment]
> > 已更新，非常感谢。
> > [ed95522](https://github.com/lwd-temp/anti-ip-attribution/commit/ed9552256ebb210b2b78aa0f9fdd88f4f9a5567d)
> 
> ## 有一个问题，单reject了httpdns.bilivideo.com之后其实还是露，根据最新的抓包来看其实还有dns.google的httpsDNS
> ![屏幕截图 2023-11-28 005102](https://private-user-images.githubusercontent.com/79711420/285930088-fb4b4297-6a81-439c-a422-833a32bc9659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDQzMDQsIm5iZiI6MTcwMTEwNDAwNCwicGF0aCI6Ii83OTcxMTQyMC8yODU5MzAwODgtZmI0YjQyOTctNmE4MS00MzljLWE0MjItODMzYTMyYmM5NjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2NTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Y2IwMzY3ODlkZjkyZjI1MmJjNzI3YWZlMTFhODFmOTQ2MzFjZjY5MzY2ZjEyYTk4ZDA5MWY5MjkzMTVjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HS2ArsIFoJS6RMo35SDaGATK56ThknwIusHjh568_n8)
> 在我抓包时就走了这几条请求去httpsDNS，但是一旦离开抓包环境，评论、动态地址直接完全泄露，排除了移动网络影响，目前还在跟进

我的想法是正确的，肯定还有其他的httpsDNS存在，离开抓包环境（http代理）之后，直接从路由器接口抓取得到的包中目的地址是bilibili国内的CDN
![62c3295faea538d3b5b134f9dfa3e1f](https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/6db28f47-2cea-418f-b5a3-8e9d25e1db3b)
![5c851a2f5bb5c7517d0616071d6c524](https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/5eca5a00-8f9e-4b27-b2c5-fedf5acd0365)
---
有没有大佬有IOS导出TLS证书的方案，我在路由器段抓包没法解密HTTPS:(

**Comment by Meina9758** [comment]
在重复抓包测试中发现，客户端与101.91.140.124通讯后才出现了国内的CDN地址，经过验证此ip的证书为*.bilivideo.com
<img width="665" alt="image" src="https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/5d3287c2-a8d7-4fe9-8e28-e1e73b2541e4">
---

在未获得地址的情况下直连了httpdns.bilivideo.com，在重复在各个DNS服务器查询域名后验证了我的猜想
<img width="348" alt="image" src="https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/15414134-2f40-4549-ba91-5544a8cea864">
---

目前应当先禁止以下地址通讯，后续跟进测试结果
-122.9.13.79
-122.9.15.129
-101.91.140.124
-101.91.140.224

**Comment by Meina9758** [comment]
它的第一个httpdns查询包竟然出现在了DNS查询之前
<img width="960" alt="image" src="https://github.com/lwd-temp/anti-ip-attribution/assets/79711420/faa3be1f-6f8c-4a51-8766-74cbbf6e3a2a">
什么原理？难道写入了hosts？这么多IP？？？

**Comment by lwd-temp** [comment]
Android 端

```java
bundle.putString(KEY_EXT_P2P_HTTPDNS_BILI_IP, "47.101.175.206;47.100.123.169;120.46.169.234;121.36.72.124;");
bundle.putString(KEY_EXT_P2P_BILIDNS_CMCC_IP, "116.63.10.135;122.9.7.134;117.185.228.108;117.144.238.29");
bundle.putString(KEY_EXT_P2P_BILIDNS_CT_IP, "122.9.13.79;122.9.15.129;101.91.140.224;101.91.140.124");
bundle.putString(KEY_EXT_P2P_BILIDNS_CU_IP, "114.116.215.110;116.63.10.31;112.64.218.119;112.65.200.117");
```

**Comment by Meina9758** [comment]
> Android 端
> 
> ```java
> bundle.putString(KEY_EXT_P2P_HTTPDNS_BILI_IP, "47.101.175.206;47.100.123.169;120.46.169.234;121.36.72.124;");
> bundle.putString(KEY_EXT_P2P_BILIDNS_CMCC_IP, "116.63.10.135;122.9.7.134;117.185.228.108;117.144.238.29");
> bundle.putString(KEY_EXT_P2P_BILIDNS_CT_IP, "122.9.13.79;122.9.15.129;101.91.140.224;101.91.140.124");
> bundle.putString(KEY_EXT_P2P_BILIDNS_CU_IP, "114.116.215.110;116.63.10.31;112.64.218.119;112.65.200.117");
> ```

直接全禁止就好了:(

**Comment by lwd-temp** [comment]
感谢贡献。
https://github.com/lwd-temp/anti-ip-attribution/commit/28aa5cdaac8b3bcdfacffecac10cc2998919cab3

**Comment by MoriMeina** [comment]
```
    const-string v2, "ijkplayer.p2p_httpdns_bili_ip"

    const-string v4, "47.101.175.206;47.100.123.169;120.46.169.234;121.36.72.124;"

    invoke-virtual {v0, v1, v4}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V

    const-string v1, "ijkplayer.p2p_bilidns_cmcc_ip"

    const-string v4, "116.63.10.135;122.9.7.134;117.185.228.108;117.144.238.29"

    .line 143
    invoke-virtual {v0, v1, v4}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V

    const-string v1, "ijkplayer.p2p_bilidns_ct_ip"

    const-string v4, "122.9.13.79;122.9.15.129;101.91.140.224;101.91.140.124"

    .line 144
    invoke-virtual {v0, v1, v4}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V

    const-string v1, "ijkplayer.p2p_bilidns_cu_ip"

    const-string v4, "114.116.215.110;116.63.10.31;112.64.218.119;112.65.200.117"
```
IOS端再露地址，目前查到的内容与之前无异
