### ISSUE TITLE
B站直播观看 解决分配海外CDN

### ISSUE THREAD

**Issue by A1ca7raz** [lwd-temp/anti-ip-attribution#53]
不像视频CDN可以通过直接替换cdn域名就可以实现切换CDN,直播CDN的连接中含有特殊的参数导致无法使用同样的方法将解析到的低速海外CDN切换至国内CDN。
我的方法是将`live.bilibili.com`和`api.live.bilibili.com`两个域名直连，可解决B站直播web端分配海外CDN的问题。
但我无法判断这样做是否存在风险。

**Comment by MoriMeina** [comment]
live.bilibili.com和api.live.bilibili.com两个域名一样是由i.w.bilicdn1.com和a.w.bilicdn1.com进行响应的，我的建议是非必要不采用www.bilibili.com与live.bilibili.com解析不一致的方案，对此我先进行测试。
nslookup live.bilibili.com
非权威应答:
名称:    i.w.bilicdn1.com
Address:  164.52.44.50
Aliases:  live.bilibili.com
          a.w.bilicdn1.com

nslookup live.bilibili.com 114.114.114.114
非权威应答:
名称:    a.w.bilicdn1.com
Addresses:  240e:f7:e01f:f1::31
          240e:978:90d:1000::76
          240e:978:90d:1000::74
          183.131.147.29
          183.131.147.27
          114.230.222.140
Aliases:  live.bilibili.com

**Comment by MoriMeina** [comment]
> live.bilibili.com和api.live.bilibili.com两个域名一样是由i.w.bilicdn1.com和a.w.bilicdn1.com进行响应的，我的建议是非必要不采用www.bilibili.com与live.bilibili.com解析不一致的方案，对此我先进行测试。 nslookup live.bilibili.com 非权威应答: 名称: i.w.bilicdn1.com Address: 164.52.44.50 Aliases: live.bilibili.com a.w.bilicdn1.com
> 
> nslookup live.bilibili.com 114.114.114.114 非权威应答: 名称: a.w.bilicdn1.com Addresses: 240e:f7:e01f:f1::31 240e:978:90d:1000::76 240e:978:90d:1000::74 183.131.147.29 183.131.147.27 114.230.222.140 Aliases: live.bilibili.com

实际分配与data.bilibili.com响应的log有关，不推荐将live加入直连

**Comment by MoriMeina** [comment]
> 不像视频CDN可以通过直接替换cdn域名就可以实现切换CDN,直播CDN的连接中含有特殊的参数导致无法使用同样的方法将解析到的低速海外CDN切换至国内CDN。 我的方法是将`live.bilibili.com`和`api.live.bilibili.com`两个域名直连，可解决B站直播web端分配海外CDN的问题。 但我无法判断这样做是否存在风险。

在论坛逛的时候看到的，油猴脚本可以部分解决问题，推荐尝试
https://greasyfork.org/zh-CN/scripts/415714-make-bilibili-great-again/code

**Comment by ocfox** [comment]
> 不像视频CDN可以通过直接替换cdn域名就可以实现切换CDN,直播CDN的连接中含有特殊的参数导致无法使用同样的方法将解析到的低速海外CDN切换至国内CDN。

我试了一下是可以的，可能更新了？
