### ISSUE TITLE
小红书失效

### ISSUE THREAD

**Issue by lcandy2** [lwd-temp/anti-ip-attribution#54]
如题，最新版app，已添加xiaohongshu.com并引入surge list

**Comment by lwd-temp** [comment]
Android端没有找到新增的API域名。

**Comment by lwd-temp** [comment]
`getui.com`和`getui.net`是第三方用户画像，`21cn.com`是第三方直播，`fengkongcloud.com`是第三方内容安全，`xhscdn.com`是CDN。

目前没有其他值得注意的域名。

**Comment by fangshuor** [comment]
我直接domain-keyword匹配xiaohongshu了_(:з」∠)_，实在懒得折腾就这样一条规则就够

**Comment by lwd-temp** [comment]
https://github.com/lwd-temp/anti-ip-attribution/commit/6d0d4a0b61f20df3def3861814ed4fe942b19bab
