### ISSUE TITLE
酷安、起点App

### ISSUE THREAD

**Issue by Yuko1997** [lwd-temp/anti-ip-attribution#62]
酷安有两个api域名
`api.coolapk.com`
`api2.coolapk.com`

起点App 章评书评区IP（大部分业务都塞在这个域名下，api book search login一大堆）
`druidv6.if.qidian.com`
疑似个人主页IP（非实时变化，看到有个login建议加上）
`ptlogin6.qidian.com`

**Comment by lwd-temp** [comment]
感谢 https://github.com/lwd-temp/anti-ip-attribution/commit/65b6194f86182a7237b805a6587b9f437f78c5b6
