### ISSUE TITLE
我不知道怎么用

### ISSUE THREAD

**Issue by MomijiHanako** [lwd-temp/anti-ip-attribution#8]
如题

**Comment by lwd-temp** [comment]
在README文件中，可以看到`配置文件`二级标题下面的文件列表，它们分别是应用于不同分流软件的配置文件。

例如：https://github.com/lwd-temp/anti-ip-attribution/blob/main/cfw.yaml `适用于Clash for Windows的配置文件预处理功能`

这时，您便需要在GitHub站内搜索`Clash for Windows`这个软件，并且寻找它的文档关于`配置文件预处理功能`的相关描述。

如果这样您仍然无法弄清楚如何使用，我实在是没有什么特别好的方法能把这个讲清楚，很抱歉，但是这里只开发配置文件，对应的软件的说明文档确实不在这里。

**Comment by MomijiHanako** [comment]
已经解决了
